### ISSUE TITLE
BUG: Treeshake doesn't work for badges

### ISSUE THREAD

**Issue by thoughtspile** [okikio/bundlejs#51] opened 2023-05-22 08:47 UTC
Looks like badges ignore treeshake option. Example with `date-fns`, trying to treeshake `isAfter`:

1. Bundlejs website: [7.27KB (gzip)](https://bundlejs.com/?q=date-fns&treeshake=%5B%7B+isAfter+%7D%5D)
2. Badge: ![](https://deno.bundlejs.com/?q=date-fns&treeshake=[{+isAfter+}]&badge=) [(link)](https://deno.bundlejs.com/?q=date-fns&treeshake=[{+isAfter+}]&badge=)
3. Full date-fns on website: [22.83KB (gzip)](https://bundlejs.com/?q=date-fns)

Moreover, local `echo 'export { isAfter } from "date-fns";' | npx esbuild --bundle --minify | gzip -c | wc -c` gives 541 bytes, maybe related to #43

**Comment by okikio** [comment] 2023-05-23 05:31
Sorry, for the delay, but after a through analysis of the bundle, it seems it keeps trying to bundle in the parser, and I can't quite figure out why it doesn't really make any sense as to why it keeps trying to bundle the parser, this might be an esbuild-wasm bug of some sort

**Comment by okikio** [comment] 2023-05-23 06:18
After a couple more experiments it seems for treeshaking to work in an ideal way it needs to have all the files it needs to traverse up front, the problem is that is double the build time versus just bundling it once. I've setup a seperate branch with the treeshaking exeriments https://bundle-git-treeshaking-fix-okikio-dev.vercel.app/?q=date-fns&treeshake=%5B%7B+isAfter+%7D%5D&config=%7B%22esbuild%22%3A%7B%22minify%22%3Afalse%7D%7D

**Comment by okikio** [comment] 2023-06-09 06:12
Good news, I seem to have a permanent solution to the problem of poor treeshaking. 
It seems this issue is caused by esbuild being unable to determine if it should include sideEffects or not. 

On a local file system esbuild can easily just look up the `package.json` files but it can't quite do that when using a virtual fs, so the solution is to just let esbuild know to use `sideEffects` if it's stated in the `package.json` file

**Comment by thoughtspile** [comment] 2023-07-02 17:38
Hi again my friend @okikio! Got a chance to roll out the fix? Still seeing odd sizes in badges:

<img width="248" alt="Снимок экрана 2023-07-02 в 20 38 25" src="https://github.com/okikio/bundlejs/assets/5262915/c4e91053-33cb-4b86-938f-485dc1f07411">

**Comment by okikio** [comment] 2023-07-03 00:15
I was able to fix it, I just hadn't found a chance to publish it. This weekend is a little hectic, I should be able to get the fix out by Tuesday or Wednesday this week

**Comment by okikio** [comment] 2023-07-03 01:44
The API hasn't been fixed yet, but here is the newly improved treeshaking 
<img width="291" alt="CleanShot 2023-07-02 at 21 44 08@2x" src="https://github.com/okikio/bundlejs/assets/17222836/0135dffa-0c17-43f1-83f2-ad3deb146f57">

**Comment by okikio** [comment] 2023-07-03 02:50
The API is now fixed as well. Treeshaking should now work properly across the website and API

**Comment by okikio** [comment] 2023-07-09 05:42
@thoughtspile Does the fix work for you?

**Comment by okikio** [comment] 2023-07-12 00:50
Since the fix seems to work ill close this issue

**Closed** 2023-07-12 00:50 UTC

**Comment by thoughtspile** [comment] 2023-07-13 11:11
Thanks @okikio, works much better now! I'm seeing some other suspicious behavior, let me open another issue

**Comment by okikio** [comment] 2023-07-13 14:44
Ok
